/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.atlastech.gestionclubdeportivos.ui.menus;

/**
 *
 * @author loren
 */
public class DashboardSocio extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DashboardSocio.class.getName());

    /**
     * Creates new form DashboardSocio
     */
    public DashboardSocio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Dashboard = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        lbHome1 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        lbMembresia = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        lbPago = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        lbReserva = new javax.swing.JLabel();
        lbSalir = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lbTitulo = new javax.swing.JLabel();
        lbPerfil = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Dashboard.setBackground(new java.awt.Color(255, 255, 255));
        Dashboard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(15, 43, 99));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(270, 530));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(29, 52, 145));
        jPanel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbHome1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbHome1.setForeground(new java.awt.Color(255, 255, 255));
        lbHome1.setText("Home");
        jPanel4.add(lbHome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 70, 40));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 320, 50));

        jPanel8.setBackground(new java.awt.Color(15, 43, 99));
        jPanel8.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel8.setMaximumSize(new java.awt.Dimension(154, 24));
        jPanel8.setPreferredSize(new java.awt.Dimension(320, 50));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbMembresia.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbMembresia.setForeground(new java.awt.Color(255, 255, 255));
        lbMembresia.setText("Membresía");
        lbMembresia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbMembresiaMouseClicked(evt);
            }
        });
        jPanel8.add(lbMembresia, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 150, 50));

        jPanel2.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 320, 50));

        jPanel6.setBackground(new java.awt.Color(15, 43, 99));
        jPanel6.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel6.setMaximumSize(new java.awt.Dimension(154, 24));
        jPanel6.setPreferredSize(new java.awt.Dimension(320, 50));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbPago.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbPago.setForeground(new java.awt.Color(255, 255, 255));
        lbPago.setText("Pagos");
        lbPago.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbPagoMouseClicked(evt);
            }
        });
        jPanel6.add(lbPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 150, 50));

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 320, 50));

        jPanel10.setBackground(new java.awt.Color(15, 43, 99));
        jPanel10.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel10.setMaximumSize(new java.awt.Dimension(154, 24));
        jPanel10.setPreferredSize(new java.awt.Dimension(320, 50));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbReserva.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbReserva.setForeground(new java.awt.Color(255, 255, 255));
        lbReserva.setText("Reservas");
        lbReserva.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbReservaMouseClicked(evt);
            }
        });
        jPanel10.add(lbReserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 150, 50));

        jPanel2.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 320, 50));

        lbSalir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbSalir.setForeground(new java.awt.Color(255, 255, 255));
        lbSalir.setText("Salir ");
        lbSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbSalirMouseClicked(evt);
            }
        });
        jPanel2.add(lbSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 600, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setOpaque(true);
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 290, -1));

        lbTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lbTitulo.setText("AtlasTech");
        jPanel2.add(lbTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 90, 30));

        lbPerfil.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbPerfil.setForeground(new java.awt.Color(255, 255, 255));
        lbPerfil.setText("Mi Perfil");
        lbPerfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbPerfilMouseClicked(evt);
            }
        });
        jPanel2.add(lbPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 150, 50));

        Dashboard.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 660));

        jPanel1.setBackground(new java.awt.Color(29, 52, 145));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Inicio Socio");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 32, 150, -1));

        Dashboard.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, 750, 130));

        jPanel18.setBackground(new java.awt.Color(15, 43, 99));
        jPanel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setBackground(new java.awt.Color(255, 255, 255));
        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("ACCESO RÁPIDO");
        jPanel18.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 150, -1));

        jButton6.setBackground(new java.awt.Color(255, 255, 255));
        jButton6.setForeground(new java.awt.Color(64, 43, 100));
        jButton6.setText("Mi Perfil");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel18.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 110, -1));

        jButton7.setBackground(new java.awt.Color(255, 255, 255));
        jButton7.setForeground(new java.awt.Color(64, 43, 100));
        jButton7.setText("Mis Reservas");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel18.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, -1, -1));

        jButton8.setBackground(new java.awt.Color(255, 255, 255));
        jButton8.setForeground(new java.awt.Color(64, 43, 100));
        jButton8.setText("Mi Membresia");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel18.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 120, -1));

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setForeground(new java.awt.Color(64, 43, 100));
        jButton5.setText("Nueva Reserva");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel18.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        Dashboard.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, 420, 220));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1070, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbSalirMouseClicked
        MenuPrincipal Salir =  new MenuPrincipal();
        Salir.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbSalirMouseClicked

    private void lbPerfilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbPerfilMouseClicked
        MenuSocioMiPerfil PerfilSocio = new MenuSocioMiPerfil();
        PerfilSocio.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbPerfilMouseClicked

    private void lbMembresiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbMembresiaMouseClicked
        MenuSocioMembresia MembresiaSocio = new MenuSocioMembresia();
        MembresiaSocio.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbMembresiaMouseClicked

    private void lbPagoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbPagoMouseClicked
        MenuSocioPagos PagosSocio = new MenuSocioPagos();
        PagosSocio.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbPagoMouseClicked

    private void lbReservaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbReservaMouseClicked
        MenuSocioReservas ReservasSocio = new MenuSocioReservas();
        ReservasSocio.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_lbReservaMouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DashboardSocio().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Dashboard;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbHome1;
    private javax.swing.JLabel lbMembresia;
    private javax.swing.JLabel lbPago;
    private javax.swing.JLabel lbPerfil;
    private javax.swing.JLabel lbReserva;
    private javax.swing.JLabel lbSalir;
    private javax.swing.JLabel lbTitulo;
    // End of variables declaration//GEN-END:variables
}
