/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.atlastech.gestionclubdeportivos.ui.menus;

/**
 *
 * @author loren
 */
public class MenuMembresia extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuMembresia.class.getName());

    /**
     * Creates new form MenuMembresiaInicio
     */
    public MenuMembresia() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        lbRegistrarMembresia = new javax.swing.JLabel();
        lbMemembresiaEditar = new javax.swing.JLabel();
        lbMembresiaCancelar = new javax.swing.JLabel();
        lbMembresiarenovar = new javax.swing.JLabel();
        lbMembresiaDetalles = new javax.swing.JLabel();
        btnGoBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(15, 43, 99));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setBackground(new java.awt.Color(230, 230, 230));
        jPanel10.setPreferredSize(new java.awt.Dimension(750, 450));

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));

        jLabel21.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setText("Inicio membresía");

        jSeparator6.setForeground(new java.awt.Color(204, 204, 204));

        lbRegistrarMembresia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbRegistrarMembresia.setForeground(new java.awt.Color(0, 0, 0));
        lbRegistrarMembresia.setText("Registrar Membresía");
        lbRegistrarMembresia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbRegistrarMembresiaMouseClicked(evt);
            }
        });

        lbMemembresiaEditar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbMemembresiaEditar.setForeground(new java.awt.Color(0, 0, 0));
        lbMemembresiaEditar.setText("Editar");
        lbMemembresiaEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbMemembresiaEditarMouseClicked(evt);
            }
        });

        lbMembresiaCancelar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbMembresiaCancelar.setForeground(new java.awt.Color(0, 0, 0));
        lbMembresiaCancelar.setText("Cancelar/Desactivar");
        lbMembresiaCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbMembresiaCancelarMouseClicked(evt);
            }
        });

        lbMembresiarenovar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbMembresiarenovar.setForeground(new java.awt.Color(0, 0, 0));
        lbMembresiarenovar.setText("Renovar");
        lbMembresiarenovar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbMembresiarenovarMouseClicked(evt);
            }
        });

        lbMembresiaDetalles.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbMembresiaDetalles.setForeground(new java.awt.Color(0, 0, 0));
        lbMembresiaDetalles.setText("Detalles Membresía");
        lbMembresiaDetalles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbMembresiaDetallesMouseClicked(evt);
            }
        });

        btnGoBack.setBackground(new java.awt.Color(0, 0, 0));
        btnGoBack.setForeground(new java.awt.Color(255, 255, 255));
        btnGoBack.setText("Volver");
        btnGoBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbMembresiaDetalles, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbRegistrarMembresia, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbMemembresiaEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbMembresiarenovar, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbMembresiaCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGoBack))))
                .addGap(0, 46, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbRegistrarMembresia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbMemembresiaEditar)
                .addGap(18, 18, 18)
                .addComponent(lbMembresiaCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbMembresiarenovar)
                .addGap(18, 18, 18)
                .addComponent(lbMembresiaDetalles)
                .addGap(18, 18, 18)
                .addComponent(btnGoBack, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 580, 410));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 770, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbRegistrarMembresiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbRegistrarMembresiaMouseClicked
       MenuMembresiaRegistro membershipRegister  = new MenuMembresiaRegistro();
       membershipRegister.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_lbRegistrarMembresiaMouseClicked

    private void lbMemembresiaEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbMemembresiaEditarMouseClicked
     MenuMembresiaEditar membershipEdit  = new MenuMembresiaEditar();
       membershipEdit.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_lbMemembresiaEditarMouseClicked

    private void lbMembresiaCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbMembresiaCancelarMouseClicked
        MenuMembresiaDesactivar membershipDeactive  = new MenuMembresiaDesactivar();
       membershipDeactive.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_lbMembresiaCancelarMouseClicked

    private void lbMembresiarenovarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbMembresiarenovarMouseClicked
       MenuMembresiaRenovar membershipRenew  = new MenuMembresiaRenovar();
       membershipRenew.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_lbMembresiarenovarMouseClicked

    private void lbMembresiaDetallesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbMembresiaDetallesMouseClicked
       MenuMembresiaDetalles membershipDetails  = new MenuMembresiaDetalles();
       membershipDetails.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_lbMembresiaDetallesMouseClicked

    private void btnGoBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoBackActionPerformed
        DashboardAdmin GoBack = new DashboardAdmin();
        GoBack.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnGoBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MenuMembresia().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGoBack;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel lbMembresiaCancelar;
    private javax.swing.JLabel lbMembresiaDetalles;
    private javax.swing.JLabel lbMembresiarenovar;
    private javax.swing.JLabel lbMemembresiaEditar;
    private javax.swing.JLabel lbRegistrarMembresia;
    // End of variables declaration//GEN-END:variables
}
