/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.atlastech.gestionclubdeportivos.ui.menus;
import javax.swing.table.DefaultTableModel;
import java.util.List;
import com.atlastech.gestionclubdeportivos.models.Entrenador;
import javax.swing.JOptionPane;

/**
 *
 * @author Mariely Florian
 */
public class MenuEntrenadorListar extends javax.swing.JPanel {
private DefaultTableModel modeloTabla;

    /**
     * Creates new form MenuEntrenadorListar
     */
    public MenuEntrenadorListar() {
        initComponents();
        configurarTabla();
        cargarDatos();
    }
    
    private void configurarTabla() {
    // Definir columnas
    String[] columnas = {"ID", "Nombre", "Teléfono", "Especialidad"};
    modeloTabla = new DefaultTableModel(columnas, 0) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false; // Hacer tabla no editable
   }
        };
    jTable1.setModel(modeloTabla); // jTable1 es el nombre de tu JTable
    }
    
    private void cargarDatos() {
    // Limpiar tabla
    modeloTabla.setRowCount(0);
    
    // Obtener lista de entrenadores (aquí usar tu DAO o Service)
    // List<Entrenador> entrenadores = entrenadorDAO.listarTodos();
    
    // Por ahora, datos de ejemplo:
    modeloTabla.addRow(new Object[]{1, "Juan Pérez", "809-555-1234", "Fútbol"});
    modeloTabla.addRow(new Object[]{2, "María López", "809-555-5678", "Natación"});
    modeloTabla.addRow(new Object[]{3, "Carlos Gómez", "809-555-9012", "Baloncesto"});
}
   


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnActualizarLista = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(390, 480));

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(29, 52, 145));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("LISTA DE ENTRENADORES");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 100));

        jSeparator4.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator4.setOpaque(true);
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 93, 460, 10));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Telefono", "Especialidad"
            }
        ));
        jTable1.setShowGrid(true);
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 410, 320));

        btnActualizarLista.setBackground(new java.awt.Color(0, 102, 51));
        btnActualizarLista.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizarLista.setText("ACTUALIZAR");
        btnActualizarLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarListaActionPerformed(evt);
            }
        });
        jPanel1.add(btnActualizarLista, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 460, 110, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 551, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnActualizarListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarListaActionPerformed
        cargarDatos();
        JOptionPane.showMessageDialog(this, "Datos actualizados", "Éxito", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnActualizarListaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarLista;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
