/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.atlastech.gestionclubdeportivos.ui.menus;
import java.awt.CardLayout;

/**
 *
 * @author loren
 */
public class MenuActividad extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuActividad.class.getName());

    /**
     * Creates new form MenuActividad
     */
    public MenuActividad() {
        initComponents();
        
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelContenedor = new javax.swing.JPanel();
        PanelMenuActividad = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        lbRegistrarActividad2 = new javax.swing.JLabel();
        lbActividadActualizar2 = new javax.swing.JLabel();
        lbActividadEliminar2 = new javax.swing.JLabel();
        lbActividadAsignaciones2 = new javax.swing.JLabel();
        lbListaActividad2 = new javax.swing.JLabel();
        btnVolverInicio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelContenedor.setBackground(new java.awt.Color(15, 43, 99));
        PanelContenedor.setLayout(new java.awt.CardLayout());

        PanelMenuActividad.setBackground(new java.awt.Color(230, 230, 230));
        PanelMenuActividad.setPreferredSize(new java.awt.Dimension(750, 450));
        PanelMenuActividad.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));

        jLabel27.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 0, 0));
        jLabel27.setText("Inicio Actividad");

        jSeparator8.setForeground(new java.awt.Color(204, 204, 204));

        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 0, 0));
        jLabel28.setText(" ");

        jLabel29.setForeground(new java.awt.Color(0, 0, 0));

        lbRegistrarActividad2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbRegistrarActividad2.setForeground(new java.awt.Color(0, 0, 0));
        lbRegistrarActividad2.setText("Registrar Actividad");
        lbRegistrarActividad2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbRegistrarActividad2MouseClicked(evt);
            }
        });

        lbActividadActualizar2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbActividadActualizar2.setForeground(new java.awt.Color(0, 0, 0));
        lbActividadActualizar2.setText("Actualizar");
        lbActividadActualizar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbActividadActualizar2MouseClicked(evt);
            }
        });

        lbActividadEliminar2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbActividadEliminar2.setForeground(new java.awt.Color(0, 0, 0));
        lbActividadEliminar2.setText("Eliminar");
        lbActividadEliminar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbActividadEliminar2MouseClicked(evt);
            }
        });

        lbActividadAsignaciones2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbActividadAsignaciones2.setForeground(new java.awt.Color(0, 0, 0));
        lbActividadAsignaciones2.setText("Asignaciones");
        lbActividadAsignaciones2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbActividadAsignaciones2MouseClicked(evt);
            }
        });

        lbListaActividad2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbListaActividad2.setForeground(new java.awt.Color(0, 0, 0));
        lbListaActividad2.setText("Lista");
        lbListaActividad2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbListaActividad2MouseClicked(evt);
            }
        });

        btnVolverInicio.setBackground(new java.awt.Color(0, 0, 0));
        btnVolverInicio.setForeground(new java.awt.Color(255, 255, 255));
        btnVolverInicio.setText("Volver a Inicio");
        btnVolverInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverInicioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel29, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                        .addComponent(jLabel28)
                        .addGap(16, 16, 16))))
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbRegistrarActividad2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbActividadActualizar2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbActividadAsignaciones2)
                            .addComponent(lbActividadEliminar2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbListaActividad2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnVolverInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 12, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbRegistrarActividad2)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGap(0, 142, Short.MAX_VALUE)
                        .addComponent(jLabel28)
                        .addGap(39, 39, 39)
                        .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(lbActividadActualizar2)
                        .addGap(18, 18, 18)
                        .addComponent(lbActividadEliminar2)
                        .addGap(18, 18, 18)
                        .addComponent(lbActividadAsignaciones2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbListaActividad2)
                        .addGap(26, 26, 26)
                        .addComponent(btnVolverInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        PanelMenuActividad.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 510, -1));

        PanelContenedor.add(PanelMenuActividad, "card2");

        getContentPane().add(PanelContenedor, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbRegistrarActividad2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbRegistrarActividad2MouseClicked
        MenuActividadRegistrar RegistrarActiv = new MenuActividadRegistrar();
        RegistrarActiv.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbRegistrarActividad2MouseClicked

    private void lbActividadActualizar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbActividadActualizar2MouseClicked
        
        MenuActividadActualizar UpdateActiv = new MenuActividadActualizar();
        UpdateActiv.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbActividadActualizar2MouseClicked

    private void lbActividadEliminar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbActividadEliminar2MouseClicked
        MenuActividadEliminar EliminarActiv = new MenuActividadEliminar();
        EliminarActiv.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbActividadEliminar2MouseClicked

    private void lbActividadAsignaciones2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbActividadAsignaciones2MouseClicked
        MenuActividadAsignaciones AsignarActiv = new MenuActividadAsignaciones();
        AsignarActiv.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbActividadAsignaciones2MouseClicked

    private void lbListaActividad2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbListaActividad2MouseClicked
        MenuActividadListar ListarActiv = new MenuActividadListar();
        ListarActiv.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbListaActividad2MouseClicked

    private void btnVolverInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverInicioActionPerformed
        DashboardAdmin InicioActiv = new DashboardAdmin();
        InicioActiv.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverInicioActionPerformed
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MenuActividad().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelContenedor;
    private javax.swing.JPanel PanelMenuActividad;
    private javax.swing.JButton btnVolverInicio;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JLabel lbActividadActualizar2;
    private javax.swing.JLabel lbActividadAsignaciones2;
    private javax.swing.JLabel lbActividadEliminar2;
    private javax.swing.JLabel lbListaActividad2;
    private javax.swing.JLabel lbRegistrarActividad2;
    // End of variables declaration//GEN-END:variables
}
