/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.atlastech.gestionclubdeportivos.ui.menus;

import java.awt.CardLayout;
import javax.swing.JPanel;
/**
 *
 * @author loren
 */
public class MenuSuscripcion extends javax.swing.JFrame {
    
    CardLayout cardLayout;
    // paneles del cardlayout 
    MenuRegistrarSuscripcion panelRegistrar;
    MenuSuscripcionCancelar panelCancelar;
    MenuSuscripcionRenovar panelRenovar;
    MenuSuscripcionConsultarSocio panelConsultar;
    MenuSuscripcionVerSuscripciones panelVer;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuSuscripcion.class.getName());

    /**
     * Creates new form MenuSuscripcion
     */
    public MenuSuscripcion() {
        initComponents();
        cardLayout = (CardLayout) jPanel4.getLayout();

        panelRegistrar = new MenuRegistrarSuscripcion();
        panelCancelar = new MenuSuscripcionCancelar();
        panelRenovar = new MenuSuscripcionRenovar();
        panelConsultar = new MenuSuscripcionConsultarSocio();
        panelVer = new MenuSuscripcionVerSuscripciones();

        jPanel4.add(panelVer, "ver");
        jPanel4.add(panelRegistrar, "registrar");
        jPanel4.add(panelCancelar, "cancelar");
        jPanel4.add(panelRenovar, "renovar");
        jPanel4.add(panelConsultar, "consultar");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnRegistrarSuscripcion = new javax.swing.JButton();
        btnRenovarSuscripcion = new javax.swing.JButton();
        btnCancelarSuscripcion = new javax.swing.JButton();
        btnVerSuscripciones = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        btnConsultarSocio = new javax.swing.JButton();
        btnGoBack = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(29, 52, 145));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("GESTIÓN DE SUSCRIPCIÓN");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(218, 218, 218)
                .addComponent(jLabel1)
                .addContainerGap(276, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 120));

        jPanel3.setBackground(new java.awt.Color(102, 153, 255));

        jLabel30.setBackground(new java.awt.Color(255, 255, 255));
        jLabel30.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("SUSCRIPCIÓN");

        jSeparator1.setBackground(new java.awt.Color(0, 51, 51));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        btnRegistrarSuscripcion.setBackground(new java.awt.Color(255, 255, 255));
        btnRegistrarSuscripcion.setForeground(new java.awt.Color(64, 43, 100));
        btnRegistrarSuscripcion.setText("Registrar suscripción ");
        btnRegistrarSuscripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarSuscripcionActionPerformed(evt);
            }
        });

        btnRenovarSuscripcion.setBackground(new java.awt.Color(255, 255, 255));
        btnRenovarSuscripcion.setForeground(new java.awt.Color(64, 43, 100));
        btnRenovarSuscripcion.setText("Renovar suscripción");
        btnRenovarSuscripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRenovarSuscripcionActionPerformed(evt);
            }
        });

        btnCancelarSuscripcion.setBackground(new java.awt.Color(255, 255, 255));
        btnCancelarSuscripcion.setForeground(new java.awt.Color(64, 43, 100));
        btnCancelarSuscripcion.setText("Cancelar suscripción");
        btnCancelarSuscripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarSuscripcionActionPerformed(evt);
            }
        });

        btnVerSuscripciones.setBackground(new java.awt.Color(255, 255, 255));
        btnVerSuscripciones.setForeground(new java.awt.Color(64, 43, 100));
        btnVerSuscripciones.setText("Ver suscripciones");
        btnVerSuscripciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerSuscripcionesActionPerformed(evt);
            }
        });

        jSeparator4.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator4.setOpaque(true);

        btnConsultarSocio.setBackground(new java.awt.Color(255, 255, 255));
        btnConsultarSocio.setForeground(new java.awt.Color(64, 43, 100));
        btnConsultarSocio.setText("Consultar Socio");
        btnConsultarSocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarSocioActionPerformed(evt);
            }
        });

        btnGoBack.setBackground(new java.awt.Color(0, 0, 0));
        btnGoBack.setForeground(new java.awt.Color(255, 255, 255));
        btnGoBack.setText("Volver");
        btnGoBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 1, Short.MAX_VALUE)
                .addGap(402, 402, 402))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(89, 89, 89)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnRenovarSuscripcion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnVerSuscripciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnRegistrarSuscripcion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCancelarSuscripcion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnConsultarSocio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(btnGoBack, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel30)
                .addGap(26, 26, 26)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(btnRegistrarSuscripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRenovarSuscripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnVerSuscripciones, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCancelarSuscripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnConsultarSocio, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGoBack, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 380, 480));

        jPanel4.setLayout(new java.awt.CardLayout());
        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 120, 420, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarSuscripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarSuscripcionActionPerformed
        java.awt.CardLayout cl = (java.awt.CardLayout) jPanel4.getLayout();
        cl.show(jPanel4, "registrar");
    }//GEN-LAST:event_btnRegistrarSuscripcionActionPerformed

    private void btnRenovarSuscripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRenovarSuscripcionActionPerformed
        java.awt.CardLayout cl = (java.awt.CardLayout) jPanel4.getLayout();
        cl.show(jPanel4, "renovar");
    }//GEN-LAST:event_btnRenovarSuscripcionActionPerformed

    private void btnCancelarSuscripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarSuscripcionActionPerformed
        java.awt.CardLayout cl = (java.awt.CardLayout) jPanel4.getLayout();
        cl.show(jPanel4, "cancelar");
    }//GEN-LAST:event_btnCancelarSuscripcionActionPerformed

    private void btnConsultarSocioActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnConsultarSocioActionPerformed
    { java.awt.CardLayout cl = (java.awt.CardLayout) jPanel4.getLayout();
        cl.show(jPanel4, "consultar");
    }//GEN-LAST:event_btnConsultarSocioActionPerformed

    private void btnVerSuscripcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerSuscripcionesActionPerformed
        java.awt.CardLayout cl = (java.awt.CardLayout) jPanel4.getLayout();
        cl.show(jPanel4, "ver");
    }//GEN-LAST:event_btnVerSuscripcionesActionPerformed

    private void btnGoBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoBackActionPerformed
        DashboardAdmin GoBack = new DashboardAdmin();
        GoBack.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnGoBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MenuSuscripcion().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarSuscripcion;
    private javax.swing.JButton btnConsultarSocio;
    private javax.swing.JButton btnGoBack;
    private javax.swing.JButton btnRegistrarSuscripcion;
    private javax.swing.JButton btnRenovarSuscripcion;
    private javax.swing.JButton btnVerSuscripciones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator4;
    // End of variables declaration//GEN-END:variables
}
