/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.atlastech.gestionclubdeportivos.ui.menus;
import com.atlastech.gestionclubdeportivos.models.Deporte;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author Mariely Florian
 */
public class MenuDeporte extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuDeporte.class.getName());

    /**
     * Creates new form MenuDeporte
     */
    private List<Deporte> listaDeportesObjetos = new ArrayList<>();
    
    /* Cargar datos de ejemplo (reemplaza más tarde por la BD) */
    private void cargarDeportesEjemplo() {
        listaDeportesObjetos.clear();
        listaDeportesObjetos.add(new Deporte(1, "Baseball", "Deporte de bate y pelota."));
        listaDeportesObjetos.add(new Deporte(2, "Baloncesto", "Juego de equipo en cancha donde se encestan balones."));
        listaDeportesObjetos.add(new Deporte(3, "Natación", "Deporte acuático en piscina."));
    }
    
    private void llenarComboDesdeObjetos(){
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
        for (Deporte d : listaDeportesObjetos) {
            model.addElement(d.getNombre());
        }
        listaDeportes.setModel(model);
    }
    
    public MenuDeporte() {
        initComponents();
        cargarDeportesEjemplo();
        llenarComboDesdeObjetos();

        // Inicializar campos de detalles como no editables
        jTextField2.setEditable(false); 
        jTextField1.setEditable(false);
        guardarCambiosDetalles.setEnabled(false);
    }
 
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        listaDeportes = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        VerDetallesDeportes = new javax.swing.JButton();
        editarDeportes = new javax.swing.JButton();
        anadirNuevoDeporte = new javax.swing.JButton();
        eliminarDeportes = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel37 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel34 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        guardarCambiosDetalles = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(15, 43, 99));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(29, 52, 145));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("GESTIÓN DE DEPORTE");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(261, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(256, 256, 256))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 120));

        jPanel3.setBackground(new java.awt.Color(102, 153, 255));

        jLabel30.setBackground(new java.awt.Color(255, 255, 255));
        jLabel30.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("SELECCIONAR DEPORTE");

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/atlastech/gestionclubdeportivos/ui/menus/Iconos/tab_32x32.png"))); // NOI18N

        listaDeportes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Baseball ", "Baloncesto ", "Natación  " }));
        listaDeportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaDeportesActionPerformed(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(0, 51, 51));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        VerDetallesDeportes.setBackground(new java.awt.Color(255, 255, 255));
        VerDetallesDeportes.setForeground(new java.awt.Color(64, 43, 100));
        VerDetallesDeportes.setText("Ver Detalles");
        VerDetallesDeportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerDetallesDeportesActionPerformed(evt);
            }
        });

        editarDeportes.setBackground(new java.awt.Color(255, 255, 255));
        editarDeportes.setForeground(new java.awt.Color(64, 43, 100));
        editarDeportes.setText("Editar");
        editarDeportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarDeportesActionPerformed(evt);
            }
        });

        anadirNuevoDeporte.setBackground(new java.awt.Color(255, 255, 255));
        anadirNuevoDeporte.setForeground(new java.awt.Color(64, 43, 100));
        anadirNuevoDeporte.setText("Añadir nuevo deporte");

        eliminarDeportes.setBackground(new java.awt.Color(255, 255, 255));
        eliminarDeportes.setForeground(new java.awt.Color(64, 43, 100));
        eliminarDeportes.setText("Eliminar");

        jSeparator4.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator4.setOpaque(true);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 1, Short.MAX_VALUE)
                .addGap(402, 402, 402))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(listaDeportes, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel31)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(editarDeportes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(eliminarDeportes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(VerDetallesDeportes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(anadirNuevoDeporte)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel31)
                    .addComponent(jLabel30))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(listaDeportes, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(VerDetallesDeportes, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(editarDeportes, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(eliminarDeportes, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(anadirNuevoDeporte, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 380, 470));

        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/atlastech/gestionclubdeportivos/ui/menus/Iconos/address_book_32x32.png"))); // NOI18N
        jPanel1.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 150, -1, -1));

        jLabel32.setBackground(new java.awt.Color(255, 255, 255));
        jLabel32.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("DETALLES DEL DEPORTE");
        jPanel1.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, 230, -1));

        jSeparator3.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator3.setOpaque(true);
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 200, 390, -1));

        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/atlastech/gestionclubdeportivos/ui/menus/Iconos/user_32x32.png"))); // NOI18N
        jPanel1.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 240, -1, -1));

        jLabel24.setBackground(new java.awt.Color(255, 255, 255));
        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Descripción: ");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 300, 230, -1));

        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/atlastech/gestionclubdeportivos/ui/menus/Iconos/cardfile_32x32.png"))); // NOI18N
        jPanel1.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 290, -1, -1));

        jLabel25.setBackground(new java.awt.Color(255, 255, 255));
        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Nombre:");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 240, 80, -1));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 330, 340, 130));
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 240, 230, 30));

        jButton9.setBackground(new java.awt.Color(255, 255, 255));
        jButton9.setForeground(new java.awt.Color(64, 43, 100));
        jButton9.setText("Editar");
        jPanel1.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 110, -1));

        guardarCambiosDetalles.setBackground(new java.awt.Color(255, 255, 255));
        guardarCambiosDetalles.setForeground(new java.awt.Color(64, 43, 100));
        guardarCambiosDetalles.setText("Guardar Cambios");
        guardarCambiosDetalles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarCambiosDetallesActionPerformed(evt);
            }
        });
        jPanel1.add(guardarCambiosDetalles, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 510, 130, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VerDetallesDeportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerDetallesDeportesActionPerformed
      
    String nombreSeleccionado = (String) listaDeportes.getSelectedItem();
    if (nombreSeleccionado == null || nombreSeleccionado.trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Selecciona un deporte primero.", "Aviso", JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    String nombreBuscado = nombreSeleccionado.trim();
    
    Deporte seleccionado = null;
    for (Deporte d : listaDeportesObjetos) {
        if (d.getNombre().equalsIgnoreCase(nombreBuscado)) {
            seleccionado = d;
            break;
        }
    }
    if (seleccionado != null) {
        // Mostrar los detalles en los campos de texto
        jTextField2.setText(seleccionado.getNombre());
        jTextField1.setText(seleccionado.getDescripcion());
        
    // Deshabilitar edición al ver detalles (se habilitará con el botón "Editar")
        jTextField2.setEditable(false); 
        jTextField1.setEditable(false);
        guardarCambiosDetalles.setEnabled(false); // Deshabilitar el botón de guardar
    } else {
        JOptionPane.showMessageDialog(this, "No se encontró información para: " + nombreBuscado, "Error", JOptionPane.ERROR_MESSAGE);
    }

    }//GEN-LAST:event_VerDetallesDeportesActionPerformed

    private void guardarCambiosDetallesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarCambiosDetallesActionPerformed
       
    String nombreActualCombo = (String) listaDeportes.getSelectedItem();
    if (nombreActualCombo == null || nombreActualCombo.trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Selecciona un deporte para guardar cambios.", "Aviso", JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    String nuevoNombre = jTextField2.getText().trim();
    String nuevaDesc = jTextField1.getText().trim();

    if (nuevoNombre.isEmpty()) {
        JOptionPane.showMessageDialog(this, "El nombre no puede quedar vacío.", "Validación", JOptionPane.WARNING_MESSAGE);
        return;
    }

    // buscar y actualizar el objeto
    boolean encontrado = false;
    for (Deporte d : listaDeportesObjetos) {
        if (d.getNombre().equalsIgnoreCase(nombreActualCombo.trim())) {
            d.setNombre(nuevoNombre);
            d.setDescripcion(nuevaDesc);
        encontrado = true;
            break;
        }
    }

    if (encontrado) {
    // refrescar combo manteniendo índice
    int idx = listaDeportes.getSelectedIndex();
    llenarComboDesdeObjetos();
    if (idx >= 0 && idx < listaDeportes.getItemCount()) {
        listaDeportes.setSelectedIndex(idx);
    }
    
    // Bloquear campos y botón de guardar después de guardar
        jTextField2.setEditable(false); 
        jTextField1.setEditable(false);
        guardarCambiosDetalles.setEnabled(false);
    
    JOptionPane.showMessageDialog(this, "Cambios guardados correctamente.");
}   else {
        JOptionPane.showMessageDialog(this, "Error al guardar cambios: Deporte no encontrado.", "Error", JOptionPane.ERROR_MESSAGE);
    }

    }//GEN-LAST:event_guardarCambiosDetallesActionPerformed

    private void listaDeportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaDeportesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listaDeportesActionPerformed

    private void editarDeportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarDeportesActionPerformed
           if (listaDeportes.getSelectedItem() == null) {
         JOptionPane.showMessageDialog(this, "Selecciona un deporte para editar.", "Aviso", JOptionPane.WARNING_MESSAGE);
         return;
    }
    // Habilitar la edición de los campos
    jTextField2.setEditable(true); 
    jTextField1.setEditable(true);
    guardarCambiosDetalles.setEnabled(true);
    }//GEN-LAST:event_editarDeportesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MenuDeporte().setVisible(true));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton VerDetallesDeportes;
    private javax.swing.JButton anadirNuevoDeporte;
    private javax.swing.JButton editarDeportes;
    private javax.swing.JButton eliminarDeportes;
    private javax.swing.JButton guardarCambiosDetalles;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JComboBox<String> listaDeportes;
    // End of variables declaration//GEN-END:variables
}
