/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.atlastech.gestionclubdeportivos.ui.menus;
import java.awt.CardLayout;

/**
 *
 * @author loren
 */
public class MenuPago extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuPago.class.getName());
    public MenuPago() {
    initComponents();

    MenuPagoSummary summary = new MenuPagoSummary(this);
    MenuPagoPayment payment = new MenuPagoPayment (this);
    MenuPagoCompletado completado = new MenuPagoCompletado (this);
    
    panelContenedor.add( summary, "Summary");
    panelContenedor.add(payment, "Payment");
    panelContenedor.add(completado,"Complete");
 
    CardLayout c = (CardLayout) panelContenedor.getLayout();
    c.show(panelContenedor, "MenuPagoSummary");
    }
    public void showPanel(String name) {
    CardLayout cl = (CardLayout) panelContenedor.getLayout();
    cl.show(panelContenedor, name);
    }

    /*public void mostrarPayment() {
    CardLayout c = (CardLayout) panelContenedor.getLayout();
    c.show(panelContenedor, "MenuPagoPayment");
    }

        public void mostrarCompletado() {
    CardLayout c = (CardLayout) panelContenedor.getLayout();
    c.show(panelContenedor, "MenuPagoCompletado");
    }*/

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenu1 = new java.awt.PopupMenu();
        panelContenedor = new javax.swing.JPanel();

        popupMenu1.setLabel("popupMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1070, 650));

        panelContenedor.setBackground(new java.awt.Color(255, 255, 255));
        panelContenedor.setLayout(new java.awt.CardLayout());
        getContentPane().add(panelContenedor, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MenuPago().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panelContenedor;
    private java.awt.PopupMenu popupMenu1;
    // End of variables declaration//GEN-END:variables
}
